#!/bin/bash
echo "Creating container..."
docker run \
    -d \
    -p 7474:7474 \
    -p 7687:7687 \
    --env NEO4J_AUTH=none \
    --name sqlpgq \
    neo4j:5.15.0

echo "Waiting 10s for neo4j to set up..."
sleep 10

echo "Importing data..."
cat src/test/resources/data/yasuda_data.cypher | docker exec -i sqlpgq cypher-shell

echo "Done."