#!/bin/bash

docker run \
    -d \
    -p 7474:7474 \
    -p 7687:7687 \
    --env NEO4J_AUTH=none \
    --name sqlpgq \
    neo4j:5.15.0

cat src/test/resources/data/yasuda_data.cypher | docker exec -i sqlpgq cypher-shell